/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio6;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author MaQuiNa1995
 */
public class Colores extends javax.swing.JFrame implements ActionListener {

    JLabel label1;
    JCheckBox check1, check2, check3;
    
    JButton boton1;
    String animales;
    
    ButtonGroup grupo1 = new ButtonGroup();

    /**
     * Creates new form Animales
     */
    public Colores() {
        initComponents();
        
        creacionVentana();
        
        creacionLabel1();
        
        creacionCheckbox1();
        creacionCheckbox2();
        creacionCheckbox3();
        
        creacionBoton1();
    }

    public void creacionVentana() {
        this.setTitle("Animales");
        this.setSize(500, 500);
        this.setLocation(500, 300);
    }

    public void creacionLabel1() {
        label1 = new JLabel();
        label1.setText("");
        label1.setBackground(Color.gray);
        label1.setBounds(10, 120, 400, 25);
        this.getContentPane().add(label1);

    }

    public void creacionCheckbox1() {
        check1 = new JCheckBox();
        check1.setText("Rojo");
        check1.setBounds(10, 10, 80, 25);
        this.getContentPane().add(check1);
        grupo1.add(check1);
    }

    public void creacionCheckbox2() {
        check2 = new JCheckBox();
        check2.setText("Verde");
        check2.setBounds(10, 30, 80, 25);
        this.getContentPane().add(check2);
                grupo1.add(check2);
    }

    public void creacionCheckbox3() {
        check3 = new JCheckBox();
        check3.setText("Azul");
        check3.setBounds(10, 50, 80, 25);
        this.getContentPane().add(check3);
                grupo1.add(check3);
    }
    
    public void creacionBoton1() {
        boton1 = new JButton();
        boton1.setText("Aceptar");
        boton1.setBounds(10, 85, 100, 25);
        this.getContentPane().add(boton1);
        boton1.addActionListener(this);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colores().setVisible(true);
            }
        });
    }
    
    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource()==boton1) {
            animales= " ";
            
            if (check1.isSelected()) {
                animales = check1.getText()+ " "+ animales;
            }
            if (check2.isSelected()) {
                animales = check2.getText()+ " "+ animales;
            }
            if (check3.isSelected()) {
                animales = check3.getText()+ " "+ animales;
            }
            label1.setText("Ha Seleccionado: "+animales);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
