/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ej_Guiado_javabeans;

import java.awt.Graphics;
import java.io.File;
import javax.swing.JFileChooser;

public class PanelPropiedades extends javax.swing.JPanel {

    File archivo = new File(jTextField1.getText());
    
    public PanelPropiedades() {
        initComponents();
        jTextField1.setEditable(false);
    }

    
    
    ImagenFondo getSelectedValue(){
        
        ImagenFondo img = new ImagenFondo();
        
        img.setOpacidad(Float.valueOf(sldOpacidad.getValue()));
        img.setRutaImagen();
        
        return img;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnAbrir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sldOpacidad = new javax.swing.JSlider();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Imagen: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 210, -1));

        btnAbrir.setText("...");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel3.setText("Opacidad:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        add(sldOpacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            jTextField1.setText(file.getAbsolutePath());
        }

        
        
    }//GEN-LAST:event_btnAbrirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSlider sldOpacidad;
    // End of variables declaration//GEN-END:variables
}
