package Operaciones;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class Operaciones extends javax.swing.JFrame {

    // Variables
    // Objetos Interfaz
    JLabel label2;
    JLabel label1;
    
    int elemento1,elemento2,suma,resta;

    JTextField inputbox1;
    JTextField inputbox2;

    JButton boton1;
    JButton boton2;

    public Operaciones() {
        
        
        
        initComponents();
        creacionVentana();
        creacionLabel1();
        creacionLabel2();
        creacionInputbox1();
        creacionInputbox2();
        creacionBoton1();
        creacionBoton2();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operaciones().setVisible(true);

            }
        });
    }

    public void creacionVentana() {
        this.setTitle("Programa Operaciones");
        this.setSize(350, 200);
        this.setLocation(100, 100);
    }

    //-------------- Labels -------------
    public void creacionLabel1() {
        label1 = new JLabel();
        label1.setText("Numero 1: ");
        label1.setBounds(10, 7, 100, 30);
        this.getContentPane().add(label1);
    }

    public void creacionLabel2() {
        label2 = new JLabel();
        label2.setText("Numero 2: ");
        label2.setBounds(10, 30, 100, 30);
        this.getContentPane().add(label2);
    }

    // -------------- InputBox ------------
    public void creacionInputbox1() {
        inputbox1 = new JTextField();
        inputbox1.setText("0");
        inputbox1.setBounds(80, 10, 100, 25);
        this.getContentPane().add(inputbox1);
    }

    public void creacionInputbox2() {
        inputbox2 = new JTextField();
        inputbox2.setText("0");
        inputbox2.setBounds(80, 33, 100, 25);
        this.getContentPane().add(inputbox2);
    }

    // --------------Botones ------------------
    public void creacionBoton1() {
        boton1 = new JButton();
        boton1.setText("Sumar");
        boton1.setBounds(10, 60, 100, 20);
        this.getContentPane().add(boton1);
        
        boton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
    }
    
    public void boton1ActionPerformed(ActionEvent evt){
        elemento1 = Integer.parseInt(inputbox1.getText());
        elemento2 = Integer.parseInt(inputbox2.getText());
        
        suma=elemento1+elemento2;
        
        JOptionPane.showMessageDialog(null, "La Suma Es: "+suma, "Suma", JOptionPane.INFORMATION_MESSAGE);
    }

    

    public void creacionBoton2() {
        boton2 = new JButton();
        boton2.setText("Restar");
        boton2.setBounds(10, 85, 100, 20);
        this.getContentPane().add(boton2);
        
        boton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        
        }
    
    public void boton2ActionPerformed(ActionEvent evt){
        elemento1 = Integer.parseInt(inputbox1.getText());
        elemento2 = Integer.parseInt(inputbox2.getText());
        
        resta=elemento1-elemento2;
        
        JOptionPane.showMessageDialog(null, "La Resta Es: "+resta, "Resta", JOptionPane.INFORMATION_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
