/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio9;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
    
public class ListaNombres extends javax.swing.JFrame implements ActionListener{

    DefaultListModel lista1;
    JButton boton1,boton2;
    JPanel panel1;
    JLabel label1;
    JList listaDefinitiva;
   
    protected String opcion;

    public ListaNombres() {
        initComponents();
        creacionVentana();
        creacionLista();
        creacionBoton1();
        creacionBoton2();
        creacionLabelJPanel();
    }

    
    public void creacionVentana() {
        this.setTitle("titulo");
        this.setSize(500, 300);
        this.setLocation(100, 100);
    }
    
    public void annadirElementos1(){
        lista1.removeAllElements();
        lista1.addElement("Akali");
        lista1.addElement("Caitlyn");
        lista1.addElement("Nunu");
        
    }
    
    public void annadirElementos2(){
        lista1.removeAllElements();
        lista1.addElement("Christian");
        lista1.addElement("Joaquin");
        lista1.addElement("Alvaro");
        
    }
    
    public void creacionLista(){
        lista1 = new DefaultListModel();
        listaDefinitiva = new JList(lista1);
        listaDefinitiva.setBounds(10, 10, 200,200);
        
    }
    
    public void creacionBoton1() {
        boton1 = new JButton();
        boton1.setText("Curso1");
        boton1.setBounds(90, 85, 100, 25);
        this.getContentPane().add(boton1);
        boton1.addActionListener(this);

    }
    
    public void creacionBoton2() {
        boton2 = new JButton();
        boton2.setText("Curso2");
        boton2.setBounds(90, 120, 100, 25);
        this.getContentPane().add(boton2);
        boton2.addActionListener(this);
    }
    
    public void creacionLabelJPanel(){
        label1 = new JLabel();
        panel1 = new JPanel();
        
        panel1.add(label1);
        label1.setText(opcion);
        
        panel1.setBounds(250, 50, 200, 50);
        
        panel1.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        
        this.getContentPane().add(panel1);
    }
    

    @Override
    public void actionPerformed(ActionEvent ae) {
        opcion = "El Texto Seleccionado Es: ";
        if (ae.getSource()== boton1) {
            annadirElementos1();
        } else if (ae.getSource()== boton2) {
            annadirElementos2();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaNombres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaNombres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
