package Proyecto_Alumnos_Grafico;
import java.io.FileNotFoundException;
import java.io.IOException;
import static java.lang.String.valueOf;
import java.util.ArrayList;

public class Principal extends javax.swing.JFrame {

    // Empieza el arranque de la ventana
    public Principal() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Alumno"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        jLabel3.setText("Apellidos:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Alumno Standar");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Alumno Doctorado");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setText("Curso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 20));

        jLabel5.setText("Numero De Curso:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 20));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1º", "2º", "3º", "4º" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 20));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 80, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 80, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 170));

        jButton1.setBackground(new java.awt.Color(204, 255, 0));
        jButton1.setText("Añadir Alumno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 0));
        jButton2.setText("Borrar Alumno");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel6.setText("Listado De Alumnos:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 560, 160));

        jButton3.setBackground(new java.awt.Color(204, 255, 0));
        jButton3.setText("Mostrar Ingresos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 255, 0));
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, -1, -1));

        jLabel7.setText("Ingresos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, 20));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Si boton jRadioButton1 y jRadioButton2 no estan seleccionados mostramos un mensaje acorde
        // a traves de la clase outputbox
        if (!jRadioButton1.isSelected() && !jRadioButton2.isSelected()) {
            ventanita.Cuadro_Warning("Error", "Ningun Tipo De Alumno Seleccionado O_o");
        } else {
            
            // Pillamos los atributos de los jtextfields
            
            String Codigo = jTextField1.getText();
            String Nombre = jTextField2.getText();
            String Apellido = jTextField3.getText();

            // Si alguno es nulo pues mostramos la inconpetencia del usuario con un mensaje acorde
            // a traves de la ya famosa output box
            if (Codigo == null | Nombre == null | Apellido == null) {
                ventanita.Cuadro_Error("Error", "Algun Campo Esta Vacio Atontao -_-");
            } else {

                // Si jRadioButton1 esta seleccionado es que el usuario quiere un alumno standar
                if (jRadioButton1.isSelected()) {
                    
                    // Aqui casteamos a String el metodo jComboBox1.getSelectedItem()
                    // que devuelve la String de la jcombobox
                    // Le metemos el resultado de esto a una  variable string
                    String Numero_Curso = (String) jComboBox1.getSelectedItem();

                    // Creamos el objeto a partir de los datos pedidos
                    Alumno alumno = new Alumno_Standar(new Identidad(Nombre, Apellido), Codigo, Numero_Curso);
                    // Añadimos el alumno al array
                    Array_Alumno.add(alumno);
                    // Seteamos el array de la clase array_lista con nuestro array actualizado
                    lista.setArray_Alumno(Array_Alumno);

                } else {

                    String Numero_Curso = jTextField4.getText();
                    int Num_Curso = Integer.parseInt(Numero_Curso);

                    Alumno alumno = new Alumno_Doctorado(new Identidad(Nombre, Apellido), Codigo, Num_Curso);
                    Array_Alumno.add(alumno);
                    lista.setArray_Alumno(Array_Alumno);
                }
                
                // seteamos a nulo el jtextarea
                jTextArea1.setText(null);
                
                // Para dejarlo limpio e imprimir el array list integro sin basurilla
                for (Alumno Objeto_Sacado : Array_Alumno) {
                    
                    // "\n" eso significa salto de linea pero manual a traves de 1 caracter
                    jTextArea1.append(Objeto_Sacado.toString() + "\n");

                }
                
                // Guardamos todo en el fichero
                try {
                    lista.Guardar_Copia("Matadero.txt");
                } catch (IOException ex) {

                }

            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        // Usamos la clase output_box para pedir a traves de una input box elnombre del alumno a borrar
        String Alumno_Borrar = ventanita.Pedir_Strings("Borrar Alumno", "Introduce El Codigo Del Alumno a Borrar");

        // Creamos un objeto basura lo unico que queremos es poner el codigo lo demas lo dejamos a nulo o 0
        Alumno al = new Alumno_Doctorado(new Identidad("", ""), Alumno_Borrar, 0);

        // Si el array contiene a al
        if (Array_Alumno.contains(al)) {
            // Lo eliminamos
            Array_Alumno.remove(al);
        }
        // seteamos a nulo el jtextarea
        jTextArea1.setText(null);

        // Para dejarlo limpio e imprimir el array list integro sin basurilla
        for (Alumno Objeto_Sacado : Array_Alumno) {
            // "\n" eso significa salto de linea pero manual a traves de 1 caracter
            jTextArea1.append(Objeto_Sacado.toString() + "\n");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        // Guardamos el Array en el fichero con el metodo Guardar_Copia
        // El try le puse porque me lo pedia el net Beans
        try {
            lista.Guardar_Copia("Matadero.txt");
        } catch (IOException ex) {

        }
        
        // Salimos De la Aplicacion
        System.exit(0);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    // Si el archivo esta vacio mostramos un mensaje acorde
        if (Array_Alumno.isEmpty()) {
            
            // Usamos la clase Output_box para mostrar una ventana con el mensaje acorde
            ventanita.Cuadro_Error("Error", "Ningun Alumno Añadido ¬¬");
        } else {
            
            // Mostrar ingresos es un metodo para calcular sumando la tasa de todos los alumnos
            // Retorna un numero double asique igualamos el metodo a un double
            double duble = lista.Mostrar_Ingresos(Array_Alumno);
            
            // Lo pasamos a String
            String Tasas = valueOf(duble);

            // Seteamos la Tasa a jlabel8 para mostrarlo y porque asi lo pedia el ejercicio
            jLabel8.setText(Tasas);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
    // Inicio Del Programa
    
    //  Te lo pone NetBeans Solo Asique no te preocupes si no lo entiendes
    // Lo del try lo puse porque me lo pidio el Netbeans sino Error xD
    public static void main(String args[]) throws FileNotFoundException{
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {

                }
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public static javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField jTextField1;
    public static javax.swing.JTextField jTextField2;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    // Instanciacion De Clases
    Output_Box ventanita = new Output_Box();
    Array_Lista lista = new Array_Lista();

    ArrayList<Alumno> Array_Alumno = new ArrayList();
}
