package Clases;
// Generated 22-feb-2016 9:20:28 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carritos generated by hbm2java
 */
public class Carritos  implements java.io.Serializable {


     private int PCarrito;
     private Usuarios usuarios;
     private Date fecha;
     private Set carrPros = new HashSet(0);

    public Carritos() {
    }

	
    public Carritos(int PCarrito) {
        this.PCarrito = PCarrito;
    }
    public Carritos(int PCarrito, Usuarios usuarios, Date fecha, Set carrPros) {
       this.PCarrito = PCarrito;
       this.usuarios = usuarios;
       this.fecha = fecha;
       this.carrPros = carrPros;
    }
   
    public int getPCarrito() {
        return this.PCarrito;
    }
    
    public void setPCarrito(int PCarrito) {
        this.PCarrito = PCarrito;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getCarrPros() {
        return this.carrPros;
    }
    
    public void setCarrPros(Set carrPros) {
        this.carrPros = carrPros;
    }




}


