package Clases;
// Generated 22-feb-2016 9:20:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Productos generated by hbm2java
 */
public class Productos  implements java.io.Serializable {


     private int PProducto;
     private Secciones secciones;
     private String descripcion;
     private Float pvp;
     private Integer stock;
     private Set carrPros = new HashSet(0);

    public Productos() {
    }

	
    public Productos(int PProducto) {
        this.PProducto = PProducto;
    }
    public Productos(int PProducto, Secciones secciones, String descripcion, Float pvp, Integer stock, Set carrPros) {
       this.PProducto = PProducto;
       this.secciones = secciones;
       this.descripcion = descripcion;
       this.pvp = pvp;
       this.stock = stock;
       this.carrPros = carrPros;
    }
   
    public int getPProducto() {
        return this.PProducto;
    }
    
    public void setPProducto(int PProducto) {
        this.PProducto = PProducto;
    }
    public Secciones getSecciones() {
        return this.secciones;
    }
    
    public void setSecciones(Secciones secciones) {
        this.secciones = secciones;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Float getPvp() {
        return this.pvp;
    }
    
    public void setPvp(Float pvp) {
        this.pvp = pvp;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    public Set getCarrPros() {
        return this.carrPros;
    }
    
    public void setCarrPros(Set carrPros) {
        this.carrPros = carrPros;
    }




}


