package Clases;
// Generated 22-feb-2016 9:20:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Secciones generated by hbm2java
 */
public class Secciones  implements java.io.Serializable {


     private int PSeccion;
     private String nombre;
     private Set productoses = new HashSet(0);

    public Secciones() {
    }

	
    public Secciones(int PSeccion) {
        this.PSeccion = PSeccion;
    }
    public Secciones(int PSeccion, String nombre, Set productoses) {
       this.PSeccion = PSeccion;
       this.nombre = nombre;
       this.productoses = productoses;
    }
   
    public int getPSeccion() {
        return this.PSeccion;
    }
    
    public void setPSeccion(int PSeccion) {
        this.PSeccion = PSeccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductoses() {
        return this.productoses;
    }
    
    public void setProductoses(Set productoses) {
        this.productoses = productoses;
    }




}


