package Clases;
// Generated 22-feb-2016 9:20:28 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int PUsuario;
     private String nombre;
     private String contrasena;
     private Set carritoses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int PUsuario) {
        this.PUsuario = PUsuario;
    }
    public Usuarios(int PUsuario, String nombre, String contrasena, Set carritoses) {
       this.PUsuario = PUsuario;
       this.nombre = nombre;
       this.contrasena = contrasena;
       this.carritoses = carritoses;
    }
   
    public int getPUsuario() {
        return this.PUsuario;
    }
    
    public void setPUsuario(int PUsuario) {
        this.PUsuario = PUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getCarritoses() {
        return this.carritoses;
    }
    
    public void setCarritoses(Set carritoses) {
        this.carritoses = carritoses;
    }




}


