package Ejercicio2;

import java.awt.Button;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

public class Colores extends JFrame implements ActionListener {

    int rojo, azul, verde;
    JButton boton2, boton3;
    Button boton1;
    Color color;
    JComboBox comboBox1, comboBox2, comboBox3;
    JLabel label1, label2, label3;
    GridLayout admin = new GridLayout(5, 1, 0, 0);
    JPanel fila1, fila2, fila3, fila4;

    public Colores() {
        initComponents();

        creacionVentana();

        creacionFila11();
        creacionFila2();
        creacionFila3();
        creacionFila4();
        comboBox1.addActionListener(this);
        comboBox2.addActionListener(this);
        comboBox3.addActionListener(this);
    }

    public void creacionVentana() {
        this.setLayout(admin);
        this.setTitle("Colores");
        this.setLocation(500, 300);
    }

    public void creacionFila11() {
        fila1 = new JPanel(new FlowLayout(FlowLayout.LEFT));
        comboBox1 = new JComboBox();
 
        label1 = new JLabel("Rojo: ");
        creacionFor(comboBox1);
        fila1.add(label1);
        fila1.add(comboBox1);
        this.add(fila1);
    }

    public void creacionFila2() {
        fila2 = new JPanel(new FlowLayout(FlowLayout.LEFT));
        comboBox2 = new JComboBox();
        label2 = new JLabel("Verde: ");
        creacionFor(comboBox2);
        fila2.add(label2);
        fila2.add(comboBox2);
        this.add(fila2);
    }

    public void creacionFila3() {
        fila3 = new JPanel(new FlowLayout(FlowLayout.LEFT));
        comboBox3 = new JComboBox();
        label3 = new JLabel("Azul: ");
        creacionFor(comboBox3);
        fila3.add(label3);
        fila3.add(comboBox3);
        this.add(fila3);

    }

    public void creacionFor(JComboBox cmpnt) {
        for (int i = 0; i < 256; i++) {
            cmpnt.addItem(i);
        }
    }

    public void creacionFila4() {

        boton1 = new Button("Muestra");
        boton2 = new JButton();
        boton3 = new JButton();

        fila4 = new JPanel(new FlowLayout(FlowLayout.LEFT));

        boton2.setText("Aceptar");
        boton3.setText("Cancelar");

        boton1.setEnabled(false);
        boton2.addActionListener(this);
        boton3.addActionListener(this);

        fila4.add(boton1);
        fila4.add(boton2);
        fila4.add(boton3);

        this.add(fila4, LEFT_ALIGNMENT);

    }
    
    public Color getColor(){
        return new Color(comboBox1.getSelectedIndex(),comboBox2.getSelectedIndex(),comboBox3.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Colores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent ae) {

        if(ae.getSource()==boton3){
            color=new Color(255,255,255);
            this.setVisible(false);
        }else{
            color=new Color(comboBox1.getSelectedIndex(),comboBox2.getSelectedIndex(),comboBox3.getSelectedIndex());
            if(ae.getSource()==boton2){                
                this.setVisible(false);
            }else{
                boton1.setBackground(color);
            }
        }

    }
}
