/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio4;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author MaQuiNa1995
 */
public class Correo extends javax.swing.JFrame {

    JButton boton1;
    JLabel label1,label2,label3;
    JTextField inputbox1,inputbox2;
    JScrollPane panelConScroll1;
    JTextArea area1;
    
    
    /**
     * Creates new form Ejercicio4
     */
    public Correo() {
        initComponents();
        
        creacionVentana();
        
        creacionBoton1();
        
        creacionLabel1();
        creacionLabel2();
        creacionLabel3();
        
        creacionInputbox1();
        creacionInputbox2();
        
        creacionInputboxcConScroll();
    }

    
    public void creacionVentana() {
        this.setTitle("Escribir Un Correo");
        this.setSize(500, 500);
        this.setLocation(500, 300);
    }
    
    public void creacionBoton1() {
        boton1 = new JButton();
        boton1.setText("Enviar");
        boton1.setBounds(250, 400, 100, 25);
        this.getContentPane().add(boton1);
    }
    
    
    //------------------ Label ------------------
    public void creacionLabel1(){
        label1 = new JLabel();
        label1.setText("Para: ");
        label1.setBounds(10, 10, 100, 25);
        this.getContentPane().add(label1);
    }
    
    public void creacionLabel2(){
        label2 = new JLabel();
        label2.setText("Asunto: ");
        label2.setBounds(10, 40, 100, 25);
        this.getContentPane().add(label2);
    }
    
    public void creacionLabel3(){
        label3 = new JLabel();
        label3.setText("Mensaje: ");
        label3.setBounds(10, 70, 100, 25);
        this.getContentPane().add(label3);
    }
    
    //------------------TextFields------------------
    
    public void creacionInputbox1() {
        inputbox1 = new JTextField();
        inputbox1.setText("");
        inputbox1.setBounds(80, 10, 100, 25);
        this.getContentPane().add(inputbox1);
    }
    
    public void creacionInputbox2() {
        inputbox2 = new JTextField();
        inputbox2.setText("");
        inputbox2.setBounds(80, 40, 100, 25);
        this.getContentPane().add(inputbox2);
    }
    
    public void creacionInputboxcConScroll() {
        
        area1 = new JTextArea();
        panelConScroll1 = new JScrollPane(area1,JScrollPane.VERTICAL_SCROLLBAR_ALWAYS,JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        
        panelConScroll1.setBounds(80, 70, 200, 100);
        area1.setBounds(80, 70, 200, 100);
        
        this.getContentPane().add(panelConScroll1);

    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Correo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Correo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Correo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Correo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Correo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
